### ISSUE TITLE
Plot implicit equation transformed by some map?

### ISSUE THREAD

**Issue by TotalVerb** [jverzani/ImplicitEquations.jl#5]
Great work on this package; I've found it quite useful.

Is it feasible/desirable under the current architecture to enable plotting the image of some implicitly defined region under a given map? For example, to plot the image of a circle `x^2 + y^2 ⩵ 1` under a map, say `z ↦ exp(z)`.

**Comment by jverzani** [comment]
Hmm, this seems like something I can do within a plot recipe. Basically the algorithm returns rectangles to plot, but these can each be transformed under the map and then plotted. Not sure how the pieces will fit together, but will give it a go. Thanks for the idea.

**Comment by jverzani** [comment]
Can you check out the `map` branch and let me know if this is what you envisioned. It isn't perfect, but might be of use.
